import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#ffb596',
        'inverse-on-surface': '#f3f0f0',
        'on-primary-fixed-variant': '#7c2e00',
        'on-background': '#1b1c1c',
        'surface-bright': '#fbf9f8',
        'on-secondary': '#ffffff',
        background: '#fbf9f8',
        'surface-container-low': '#f6f3f2',
        'on-secondary-container': '#294f83',
        'primary-fixed-dim': '#ffb596',
        'primary-fixed': '#ffdbcd',
        'on-secondary-fixed': '#001b3c',
        'surface-tint': '#a33e00',
        'on-primary': '#ffffff',
        secondary: '#3a5f94',
        'surface-variant': '#e4e2e1',
        'on-surface-variant': '#5a4136',
        'secondary-fixed-dim': '#a7c8ff',
        surface: '#fbf9f8',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#9fc2fe',
        'surface-container-high': '#eae8e7',
        'secondary-fixed': '#d5e3ff',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'tertiary-container': '#ff634f',
        'outline-variant': '#e3bfb1',
        'on-tertiary-fixed-variant': '#930000',
        'surface-dim': '#dcd9d9',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#561d00',
        'on-error': '#ffffff',
        'primary-container': '#ff6600',
        'on-secondary-fixed-variant': '#1f477b',
        'tertiary-fixed': '#ffdad4',
        tertiary: '#c00000',
        'surface-container-highest': '#e4e2e1',
        'on-tertiary-container': '#660000',
        'inverse-surface': '#303030',
        'on-primary-fixed': '#360f00',
        'surface-container': '#f0eded',
        'on-surface': '#1b1c1c',
        'tertiary-fixed-dim': '#ffb4a8',
        primary: '#a33e00',
        outline: '#8e7164',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#410000',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

export default config;
